from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "data" / "analysis.json"
OUTPUT_PATH = ROOT / "index.html"

TEMPLATE = r'''<!doctype html>
<html lang="id">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>prabowo.speeches / word index</title>
<style>
:root{--bg:#090d0b;--panel:#0e1611;--panel2:#121e15;--ink:#d9f4df;--muted:#7d9985;--dim:#4e6956;--line:#21372a;--strong:#365641;--green:#91ffae;--green2:#4cb875;--amber:#e5c77d;--mono:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono",monospace}
*{box-sizing:border-box}html{background:var(--bg);color-scheme:dark}body{margin:0;background:var(--bg);color:var(--ink);font:13px/1.5 var(--mono);-webkit-font-smoothing:antialiased}button,input,select{font:inherit}.shell{width:min(1200px,calc(100% - 32px));margin:auto;padding:18px 0 34px}.top,.foot{display:flex;justify-content:space-between;gap:16px;align-items:center;color:var(--muted);font-size:11px}.top{padding-bottom:13px;border-bottom:1px solid var(--line)}.dim{color:var(--dim)}.green{color:var(--green)}.ok:before{content:"";display:inline-block;width:6px;height:6px;border-radius:50%;background:var(--green2);margin:0 7px 1px 0}
.overview{display:grid;grid-template-columns:minmax(0,1fr) minmax(400px,1.05fr);gap:30px;padding:34px 0 27px;border-bottom:1px solid var(--line)}.eyebrow{color:var(--green2);font-size:10px;letter-spacing:.08em;margin-bottom:10px}h1{font-size:clamp(25px,3.6vw,39px);line-height:1.04;letter-spacing:-.07em;font-weight:600;margin:0}.lede{max-width:560px;color:var(--muted);font-size:11px;margin:15px 0 0}.metrics{display:grid;grid-template-columns:repeat(3,1fr);align-self:end;border-top:1px solid var(--line);border-left:1px solid var(--line)}.metric{min-height:82px;padding:13px 14px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.metric label{display:block;color:var(--dim);font-size:9px;text-transform:uppercase;letter-spacing:.1em}.metric b{display:block;color:var(--ink);font-size:25px;line-height:1;margin-top:9px;font-weight:500;letter-spacing:-.06em}.metric:first-child b{color:var(--green)}.metric small{display:block;color:var(--dim);font-size:9px;margin-top:8px}
.toolbar{display:flex;align-items:center;flex-wrap:wrap;gap:8px 18px;min-height:63px;border-bottom:1px solid var(--line)}.control{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:10px}.control label{color:var(--dim)}input,select{min-height:33px;border:1px solid var(--strong);border-radius:2px;background:var(--panel);color:var(--ink);padding:7px 9px;outline:none}input{width:min(280px,60vw)}input::placeholder{color:var(--dim)}input:focus,select:focus{border-color:var(--green2);box-shadow:0 0 0 2px #4cb8751a}.toggle{min-height:33px;padding:0 10px;border:1px solid var(--line);background:transparent;color:var(--muted);cursor:pointer}.toggle:hover,.toggle.active{border-color:var(--green2);color:var(--green)}.scope-note{margin-left:auto;color:var(--dim);font-size:10px}
.grid{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(315px,.85fr);gap:30px;padding-top:26px}.head{display:flex;justify-content:space-between;align-items:baseline;min-height:34px;border-bottom:1px solid var(--strong)}h2{font-size:12px;font-weight:600;margin:0}.head span{color:var(--dim);font-size:9px}.sub{color:var(--muted);font-size:10px;margin:8px 0 13px}.wordhead,.wordrow{display:grid;grid-template-columns:30px minmax(90px,1fr) minmax(90px,1.6fr) 52px 52px;gap:10px;align-items:center}.wordhead{min-height:29px;border-bottom:1px solid var(--line);color:var(--dim);font-size:9px;text-transform:uppercase;letter-spacing:.08em}.wordrow{width:100%;min-height:39px;border:0;border-bottom:1px solid #21372ab3;background:transparent;color:var(--ink);text-align:left;cursor:pointer}.wordrow:hover,.wordrow:focus-visible,.wordrow.selected{background:var(--panel2);outline:none}.wordrow.selected .word{color:var(--green)}.rank,.count,.coverage{color:var(--muted);font-size:10px}.word{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.meter{height:7px;background:#17261b;overflow:hidden}.meter i{display:block;height:100%;min-width:2px;background:var(--green2)}.wordrow.selected .meter i{background:var(--green)}
.detail{margin-top:25px;padding-top:14px;border-top:1px solid var(--strong)}.detailtitle{display:flex;align-items:baseline;gap:12px}.detailword{color:var(--green);font-size:20px;letter-spacing:-.06em}.detailtitle small{color:var(--muted);font-size:10px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0}.stat{padding:8px 9px;background:var(--panel);border:1px solid var(--line)}.stat b{display:block;font-size:15px;font-weight:500}.stat small{color:var(--dim);font-size:8px;text-transform:uppercase;letter-spacing:.08em}.break{border-top:1px solid var(--line)}.breakrow{display:grid;grid-template-columns:1fr 45px;gap:10px;padding:6px 0;border-bottom:1px solid var(--line);color:var(--muted);font-size:9px}.breakrow strong{color:var(--ink);font-weight:500}.breakrow span:last-child{text-align:right;color:var(--green)}
.sources{border-top:1px solid var(--line)}.source{display:grid;grid-template-columns:1fr auto;gap:4px 12px;padding:12px 0;border-bottom:1px solid var(--line);cursor:pointer}.source:hover,.source:focus-visible,.source.active{background:var(--panel2);outline:none}.source-title{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--ink);font-size:10px}.source-meta{color:var(--muted);font-size:9px}.tag{color:var(--amber)}.source-count{color:var(--green);font-size:10px;white-space:nowrap}.bar{grid-column:1/-1;height:3px;background:#17261b}.bar i{display:block;height:100%;background:var(--green2)}.source-open{display:inline-block;margin-top:11px;color:var(--green2);font-size:9px;text-decoration:none}.source-open:hover{color:var(--green);text-decoration:underline}details{margin-top:22px;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}summary{padding:11px 0;color:var(--muted);cursor:pointer;font-size:9px;list-style:none}summary::-webkit-details-marker{display:none}summary:before{content:"[+] ";color:var(--green2)}details[open] summary:before{content:"[-] "}.method{max-width:850px;padding:0 0 13px;color:var(--muted);font-size:9px}.method code,.method a{color:var(--green2)}.foot{padding-top:15px;font-size:9px}.foot a{color:var(--green2);text-decoration:none}.empty{padding:22px 0;color:var(--dim)}
@media(max-width:860px){.overview,.grid{grid-template-columns:1fr}.scope-note{width:100%;margin-left:0}}@media(max-width:560px){.shell{width:calc(100% - 20px);padding-top:10px}.top,.foot{align-items:flex-start;flex-direction:column}.metric{padding:10px 8px}.metric b{font-size:19px}.wordhead,.wordrow{grid-template-columns:24px minmax(82px,1fr) minmax(55px,1fr) 42px;gap:7px}.wordhead>:last-child,.wordrow>:last-child{display:none}.stats{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="shell">
<header class="top"><div><span class="dim">~/research/</span><span class="green">prabowo-wordcount</span><span class="dim"> $ ./index</span></div><div class="ok green">dataset loaded</div></header>
<main>
<section class="overview"><div><div class="eyebrow">// YOUTUBE CAPTIONS · ID · SURFACE FORM</div><h1>prabowo.speeches<br>/ word index</h1><p class="lede">Ten recent speech uploads. Counted from the Indonesian YouTube caption track inside an approximate speech window. All selected tracks are auto-generated.</p></div><div class="metrics"><div class="metric"><label>speeches</label><b id="mVideos">—</b><small>selected uploads</small></div><div class="metric"><label>tokens</label><b id="mTokens">—</b><small>event markers removed</small></div><div class="metric"><label>vocabulary</label><b id="mUnique">—</b><small>unique surface forms</small></div></div></section>
<section class="toolbar"><div class="control"><label for="scope">scope</label><select id="scope"><option value="all">all speeches</option></select></div><div class="control"><label for="search">find</label><input id="search" type="search" placeholder="search a word  /" autocomplete="off"></div><button class="toggle" id="lexical" type="button" aria-pressed="false">filter kata umum</button><span class="scope-note" id="scopeNote">pooled count · repeated words retained</span></section>
<section class="grid"><section><div class="head"><h2>top words</h2><span id="wordMeta">—</span></div><p class="sub">klik kata untuk distribusi antar-pidato.</p><div class="wordhead"><span>#</span><span>word</span><span>relative</span><span>count</span><span>speeches</span></div><div id="words"></div><div class="detail" aria-live="polite"><div class="detailtitle"><span class="detailword" id="dWord">—</span><small id="dCount">select a word</small></div><div class="stats"><div class="stat"><b id="dRate">—</b><small>per 1.000 token</small></div><div class="stat"><b id="dCoverage">—</b><small>speech coverage</small></div><div class="stat"><b id="dRank">—</b><small>rank in scope</small></div></div><div class="break" id="breakdown"></div></div></section><aside><div class="head"><h2>speech set</h2><span>newest first</span></div><p class="sub">pilih satu untuk mengisolasi hitungan.</p><div class="sources" id="sources"></div><div id="openSource"></div></aside></section>
<details><summary>method + provenance</summary><div class="method"><p>Source: <code>youtube-transcript-api</code>, language <code>id</code>, auto-generated track. Bracketed events such as <code>[musik]</code> and <code>[tepuk tangan]</code> are removed. Unicode NFC, casefold, and Unicode-aware tokenization are applied. No deduplication is performed.</p><p>Approximate speech windows were selected where uploads include event opening, music, or closing material. Counts describe caption windows, not verified audio ground truth. Raw snippets, source metadata, and analysis scripts remain in the workspace.</p><a href="https://github.com/jdepoix/youtube-transcript-api" target="_blank" rel="noreferrer">source: youtube-transcript-api ↗</a></div></details>
</main><footer class="foot"><span><span class="dim">/</span> focus search · <span class="dim">esc</span> clear</span><a href="https://www.youtube.com/@SekretariatPresiden" target="_blank" rel="noreferrer">official source channel ↗</a></footer>
</div>
<script>
const DATA=__DATA__;const STOP=new Set(["yang","dan","di","ke","dari","untuk","dengan","ini","itu","pada","dalam","adalah","akan","ada","atau","bagi","sebagai","oleh","para","sudah","sangat","juga","lebih","tidak","kita","saya","kami","ya","kan","lagi","hanya","semua","bisa"]);const state={scope:"all",query:"",lexical:false,word:null};const $=id=>document.getElementById(id);const fmt=n=>new Intl.NumberFormat("id-ID").format(n);const list=()=>[...DATA.sources].sort((a,b)=>b.date.localeCompare(a.date));const active=()=>state.scope==="all"?DATA.sources:DATA.sources.filter(s=>s.id===state.scope);
function aggregate(){const a={};for(const s of active())for(const [w,n] of Object.entries(s.counts)){if(state.lexical&&STOP.has(w))continue;a[w]=(a[w]||0)+n}return Object.entries(a).map(([word,count])=>({word,count,speechCount:active().filter(s=>s.counts[word]).length})).sort((a,b)=>b.count-a.count||a.word.localeCompare(b.word))}
function metrics(){const ss=active(),total=ss.reduce((n,s)=>n+s.token_count,0),unique=new Set(ss.flatMap(s=>Object.keys(s.counts))).size;$("mVideos").textContent=fmt(ss.length);$("mTokens").textContent=fmt(total);$("mUnique").textContent=fmt(unique);$("scopeNote").textContent=state.scope==="all"?"pooled count · repeated words retained":"single speech · repeated words retained"}
function scopeOptions(){const el=$("scope"),current=state.scope;el.innerHTML='<option value="all">all speeches</option>';for(const s of list()){const o=document.createElement("option");o.value=s.id;o.textContent=`${s.date} · ${s.title}`;el.append(o)}el.value=current}
function detail(rows){const x=rows.find(r=>r.word===state.word)||rows[0];if(!x){$("dWord").textContent="—";$("dCount").textContent="select a word";$("breakdown").innerHTML="";return}state.word=x.word;const total=rows.reduce((n,r)=>n+r.count,0),rank=rows.findIndex(r=>r.word===x.word)+1;$("dWord").textContent=x.word;$("dCount").textContent=`${fmt(x.count)} occurrences`;$("dRate").textContent=total?(x.count/total*1000).toFixed(2):"0";$("dCoverage").textContent=`${x.speechCount}/${active().length}`;$("dRank").textContent=`#${rank}`;$("breakdown").innerHTML=active().map(s=>({s,count:s.counts[x.word]||0})).sort((a,b)=>b.count-a.count).map(x=>`<div class="breakrow"><span><strong>${x.s.date}</strong> · ${x.s.channel}</span><span>${fmt(x.count)}</span></div>`).join("")}
function words(){const rows=aggregate(),q=state.query.trim().toLowerCase(),filtered=rows.filter(r=>!q||r.word.includes(q)),shown=filtered.slice(0,40),max=shown[0]?.count||1,total=rows.reduce((n,r)=>n+r.count,0);$("wordMeta").textContent=`${fmt(filtered.length)} matches · ${fmt(total)} tokens`;const el=$("words");el.innerHTML="";if(!shown.length){el.innerHTML='<div class="empty">no matching words</div>';detail([]);return}if(!state.word||!rows.some(r=>r.word===state.word))state.word=shown[0].word;for(const [i,r] of shown.entries()){const b=document.createElement("button");b.className=`wordrow${r.word===state.word?" selected":""}`;b.innerHTML=`<span class="rank">${String(i+1).padStart(2,"0")}</span><span class="word">${r.word}</span><span class="meter"><i style="width:${r.count/max*100}%"></i></span><span class="count">${fmt(r.count)}</span><span class="coverage">${r.speechCount}/${active().length}</span>`;b.onclick=()=>{state.word=r.word;render()};el.append(b)}detail(rows)}
function speechList(){const ss=list(),max=Math.max(...ss.map(s=>s.token_count),1),el=$("sources");el.innerHTML=ss.map(s=>`<div class="source${state.scope===s.id?" active":""}" tabindex="0" role="button" data-id="${s.id}"><div><div class="source-title">${s.title}</div><div class="source-meta">${s.date} · ${s.channel} · <span class="tag">auto</span></div></div><div class="source-count">${fmt(s.token_count)}</div><div class="bar"><i style="width:${s.token_count/max*100}%"></i></div></div>`).join("");for(const item of el.querySelectorAll(".source")){const pick=()=>{state.scope=item.dataset.id;state.word=null;render()};item.onclick=pick;item.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();pick()}}}const chosen=state.scope==="all"?null:DATA.sources.find(s=>s.id===state.scope);$("openSource").innerHTML=chosen?`<a class="source-open" href="${chosen.url}" target="_blank" rel="noreferrer">open source video ↗</a>`:""}
function render(){scopeOptions();metrics();words();speechList();$("lexical").classList.toggle("active",state.lexical);$("lexical").setAttribute("aria-pressed",String(state.lexical))}$("scope").onchange=e=>{state.scope=e.target.value;state.word=null;render()};$("search").oninput=e=>{state.query=e.target.value;words()};$("lexical").onclick=()=>{state.lexical=!state.lexical;state.word=null;render()};document.onkeydown=e=>{if(e.key==="/"&&document.activeElement!==$("search")){e.preventDefault();$("search").focus()}if(e.key==="Escape"){$("search").value="";state.query="";$("search").blur();words()}};render();
</script>
</body>
</html>
'''

def main() -> None:
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")
    OUTPUT_PATH.write_text(TEMPLATE.replace("__DATA__", payload), encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}")
    print(f"embedded {data['totals']['video_count']} sources / {data['totals']['total_tokens']} tokens")

if __name__ == "__main__":
    main()
